import type { PluginAttachmentSourceContribution } from "./contracts.js";

export {
  PluginAttachmentItemSchema,
  PluginAttachmentSearchPayloadSchema,
  type PluginAttachmentItem,
  type PluginAttachmentSearchPayload,
} from "./attachments.js";
export type { PluginAttachmentSourceContribution, PluginHandlerContext } from "./contracts.js";
export { defineRpc, type PluginRpcContract } from "./rpc.js";
export {
  PLUGIN_FORGE_SERVICE_METHODS,
  ForgeAuthenticationError,
  ForgeCliMissingError,
  ForgeCommandError,
  compareTimelineItems,
  computeChecksStatus,
  createUnavailableSearchResult,
  defineForgeServerProvider,
  normalizeForgeSearchKinds,
  parseOptionalTime,
  type CheckAnnotation,
  type CheckDetails,
  type CheckFailedJob,
  type CreatePullRequestOptions,
  type CurrentPullRequestStatus,
  type DisablePullRequestAutoMergeOptions,
  type EnablePullRequestAutoMergeOptions,
  type ForgeAuthState,
  type ForgeCommandFailureParams,
  type ForgeReadOptions,
  type ForgeService,
  type ForgeSpecificStatusFacts,
  type GetCheckDetailsOptions,
  type GetPullRequestOptions,
  type GetPullRequestTimelineOptions,
  type IssueSummary,
  type ListIssuesOptions,
  type ListPullRequestsOptions,
  type MergePullRequestOptions,
  type PipelineDetails,
  type PipelineJob,
  type PipelineJobStatus,
  type PipelineStage,
  type PluginForgeDefinition,
  type PluginForgeErrorKind,
  type PluginForgeSerializedError,
  type PluginForgeServerProviderContribution,
  type PluginForgeServerProviderDescriptor,
  type PluginForgeServerService,
  type PluginForgeServiceMethod,
  type PullRequestAutoMergeResult,
  type PullRequestCheck,
  type PullRequestChecksStatus,
  type PullRequestCheckStatus,
  type PullRequestCheckoutRef,
  type PullRequestCheckoutTarget,
  type PullRequestCommandStatus,
  type PullRequestCreateResult,
  type PullRequestMergeable,
  type PullRequestMergeMethod,
  type PullRequestMergeResult,
  type PullRequestReviewDecision,
  type PullRequestSummary,
  type PullRequestTimeline,
  type PullRequestTimelineCommentLocation,
  type PullRequestTimelineError,
  type PullRequestTimelineErrorKind,
  type PullRequestTimelineItem,
  type PullRequestTimelineReviewState,
  type SearchIssuesAndPrsOptions,
  type SearchResult,
} from "./forge.js";

export function defineAttachmentSource<Definition extends PluginAttachmentSourceContribution>(
  definition: Definition,
): Definition {
  return definition;
}
